### ISSUE TITLE
Example App link broken on the website

### ISSUE THREAD

**Issue by hamlim** [callstack-io/linaria#104]
**Do you want to request a *feature* or report a *bug*?**
Bug (with website)

Currently at the bottom of the website in the Docs and Examples section, the link to an `example app` is broken, it points to https://github.com/callstack-io/linaria/tree/master/example.

**Comment by thymikee** [comment]
We decided to remove the example in favor of presenting the website as an example. You'll find it [here](https://github.com/callstack-io/linaria/tree/master/website).
Nevertheless, this needs a fix, thanks for reporting (we accept PRs 🙂)
